### ISSUE TITLE
db scripts should fetch latest db release

### ISSUE THREAD

**Issue by josefalcon** [m50dkp/trinitycore-docker#2]
Releases https://github.com/TrinityCore/TrinityCore/releases

**Comment by kirbysayshi** [comment]
Luckily, this is no longer needed! As long as you update the source code and recompile, the [worldserver will actually update the database itself](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130092/Databases+Installation#DatabasesInstallation-KeepingtheDBuptodate)!
