### ISSUE TITLE
DB init error

### ISSUE THREAD

**Issue by drewmullen** [m50dkp/trinitycore-docker#7]
Following the readme as guide for container creation, i get the following error:
`Creating tables...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Creating auth...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Creating characters...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Creating world...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Applying updates...
cat: /usr/local/trinitycore/TrinityCore/sql/updates/world/*.sql: No such file or directory
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Finished initializing database`
 
to recreate issue:
`docker build -t trinitycore-db .`

`docker run --name tc-mysql-data trinitycore-db data`

`docker run --rm -ti --volumes-from tc-mysql-data -e MYSQL_ROOT_PASSWORD=password trinitycore-db init`

**Comment by drewmullen** [comment]
as a sanity check, i also ran the server-simple.sh and got the same errors

$

**Comment by drewmullen** [comment]
i forgot to include '-it' in the data container creation command

**Comment by drewmullen** [comment]
sorry for closing and reopening... just trying to figure out how this was designed :D i may make 1 or 2 suggestions to the readme once i get it working

**command**:
$ ./server-simple.sh /home/wow/server-azerothcore/world-server/maps/ 192.168.0.152

**error**:
Creating tables...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

error is repeated for all tables (auth, world, characters)


**bonus question**: is the $1 "DATA_DIR" variable used anywhere? i cant find it... was it missnamed? should it actually be "MAPS_DIR" ?

**Comment by josefalcon** [comment]
`DATA_DIR` looks like it was used, but some changes invalidated it and it wasn't removed.

If it can't connect through the socket, maybe the socket isn't open. Are you sure mysql is running?

**Comment by drewmullen** [comment]
doesnt it run in the container?

**Comment by josefalcon** [comment]
it does. 

it looks like we used mariadb:latest in the docker file :( we didn't know what we were doing back then. so maybe something changed. running the container manually i can see that sock file does not exist.

**Comment by drewmullen** [comment]
maybe there is a previous version of mariaDB to use, as a work around?

**Comment by kirbysayshi** [comment]
@drewmullen I know it's been like... 3+ years, but if you're still interested, the project has been completely rewritten to be drastically simpler and easier to maintain. The database now inits itself!

This is all that's required to get a working trinitycore running:

```sh
./action tc-fetch
./action tc-build
./action tc-db-fetch
CLIENT_DIR=/absolutepath/to/installed/WoW3.3.5a ./action tc-extract
docker-compose up
```

Good luck! And let us know if you revisit :)
